### ISSUE TITLE
How can I enable this in Projectile's Ivy?

### ISSUE THREAD

**Issue by ema2159** [asok/all-the-icons-ivy#10]
I tried this 

```elisp
  (setq all-the-icons-ivy-file-commands
	'(counsel-find-file
	  counsel-file-jump
	  counsel-recentf
	  projectile-find-file
	  projectile-find-dir))
```
but it didn't work.

**Comment by honmaple** [comment]
use `projectile-completing-read` instead of  `projectile-find-file`

**Comment by ema2159** [comment]
> use `projectile-completing-read` instead of `projectile-find-file`

Awesome! That's just what I wanted thanks!
