### ISSUE TITLE
all-the-icons-ivy requires after-init hook to work

### ISSUE THREAD

**Issue by ianyepan** [asok/all-the-icons-ivy#11]
As titled, from my experience in order for all-the-icons-ivy to work as expected, the setup needs to be done in an after-init hook. I suspect this is to prevent being overridden by other configs such as ivy-posframe.

Consider chainging the documentation for configuration to:
```emacs-lisp
(use-package all-the-icons-ivy
  :hook (after-init . all-the-icons-ivy-setup))
```

**Comment by asok** [comment]
TBH I a noob where it comes to use-package.
Isn't `:hook` a quite recent addition? Maybe considering older versions of use-package this would be better?
```el
(use-package all-the-icons-ivy
  :init (add-hook 'after-init-hook 'all-the-icons-ivy-setup))
```

**Comment by ianyepan** [comment]
From my experience, yes, they are equivalent.

**Comment by asok** [comment]
Thanks for pointing that out.
