### ISSUE TITLE
Directory symbol doesn't show up as in all-the-icons

### ISSUE THREAD

**Issue by hisnawi** [asok/all-the-icons-ivy#12]
I noticed that a directory symbol in all-the-icons-ivy shows is as a blank page symbol that is flipped on the corner. Which is completely different from the regular directory symbol which shows up in all-the-icons.
Is that expected?

**Comment by asok** [comment]
Can you provide a screenshot of this glitch?

**Comment by hisnawi** [comment]
I found that the issue got resolved by implementing this:
https://github.com/asok/all-the-icons-ivy/issues/7
