### ISSUE TITLE
Causes emacs crash

### ISSUE THREAD

**Issue by sachdevaprash** [asok/all-the-icons-ivy#2]
**Software versions**
emacs:                 github emacs-26 branch (Labeled 26.1 - current) 
ivy:                      2018040.1858 (Melpa latest)
all-the-icons:       2018.0125.757 (Melpa latest)
all-the-icons-ivy: 20180225.630 (Melpa latest)

Code used:
```
(require 'all-the-icons-ivy)
(ivy-set-display-transformer 'ivy-switch-buffer 'all-the-icons-ivy-buffer-transformer)
```

Calling `ivy-switch-buffer` crashed emacs with a segmentation fault

**Comment by asok** [comment]
Does it crash for you if you use solely all-the-icons-ivy?

**Comment by sachdevaprash** [comment]
I cannot seem to reproduce the bug anymore. I'll open it if it happens again.
