### ISSUE TITLE
display correct icon for directories

### ISSUE THREAD

**Issue by wedens** [asok/all-the-icons-ivy#5]
Observed:
`counsel-find-file` displays some incorrect generic icons for directories:
![image](https://user-images.githubusercontent.com/697162/47768950-a9a04880-dd0c-11e8-9e32-efa999362f91.png)

Expected: Detect when candidate is a directory and use `(all-the-icons-octicon "file-directory")` icon.

**Comment by asok** [comment]
Sorry for a late response.
About your issue - I'm just calling all-the-icons' function `all-the-icons-icon-for-file`. And this is the icon returned by it. I think that we could improve here by having the directory icon have colors instead of a simple shades.

**Comment by asok** [comment]
@wedens I've pushed version 0.4.0 that should look better:
![screen shot 2019-01-14 at 09 50 47](https://user-images.githubusercontent.com/120457/51103118-e34c0000-17e1-11e9-82de-03a09da2f6cc.png)

**Comment by wedens** [comment]
@asok thanks!
