### ISSUE TITLE
Configurable spacer

### ISSUE THREAD

**Issue by bjorntropf** [asok/all-the-icons-ivy#9]
It would be great to be able to configure the spacer between icons and text by a variable. The default could still be a tab "\t" but with my current emacs theme, a simple space " " looks much better. At the moment I have to replace 2 functions to do so, which is not ideal :-)

**Comment by yanghaoxie** [comment]
I am facing the same situation.

**Comment by asok** [comment]
Sorry for the late response :) let me know if ff469fe works for you.
